name: Ejecutar pruebas uni

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Puedes cambiar la versión si deseas

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
